name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: 'AB#.*'
          helpMessage: 'Please include "AB#" in the PR title (e.g., AB#123: My PR title)'
